# Generated by Django 6.0.4 on 2026-04-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctor_ward_remove_patient_created_at_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stock_quantity', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
